
The following have been reloaded with a version change:
  1) gcc/10.2.0 => gcc/13.0.1

==> Error: Spec 'gcc@13.2.0' matches no installed packages.
==> Error: Spec 'intel-oneapi-compilers' matches no installed packages.
Traceback (most recent call last):
  File "/burg/ccce/users/eav2136/projects/core_level_spectroscopy/01_peommp2_cbe/imds_1e.py", line 10, in <module>
    imds = _IMDS(mycc)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/cc/eom_kccsd_rhf.py", line 2402, in __init__
    eris = cc.ao2mo()
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/cc/kccsd_rhf.py", line 674, in ao2mo
    return _ERIS(self, mo_coeff)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/cc/kccsd_rhf.py", line 890, in __init__
    self.oooo[kp, kr, kq, :, :, :, :] = buf_kpt[:, :, :nocc, :nocc] / nkpts
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 1009, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 280, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: [Errno 122] Can't synchronously write data (file write failed: time = Fri Jan 26 15:24:31 2024
, filename = '/burg/ccce/users/eav2136/projects/core_level_spectroscopy/01_peommp2_cbe/tmp/tmp1x445b7t', file descriptor = 7, errno = 122, error message = 'Disk quota exceeded', buf = 0x3a28ab0, total write size = 1679616, bytes this sub-write = 1679616, bytes actually written = 18446744073709551615, offset = 0)
Exception ignored in: <function H5TmpFile.__del__ at 0x155540541120>
Traceback (most recent call last):
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/lib/misc.py", line 914, in __del__
    self.close()
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/files.py", line 586, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 360, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
